version: 0.2

phases:
  pre_build:
    commands:
      - echo "Buildspec is running the install phase"
      - npm install
  build:
    commands:
      - echo "Buildspec is running the build phase"
      - npm run start

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: ./