version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Running build process..."
      # Aquí irían los comandos que necesitas para construir tu aplicación.
  post_build:
    commands:
      - echo "Running deployment process..."
      - npm run start # Ejecuta el comando start solo en el despliegue

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: ./